baseURL = "https://dalamjaringan.github.io"
title = "Hanif-log"
theme = "etch"
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "catatan harian hanif"
  copyright = "Hak cipta © 2022 | [menjelangpadam](https://instagram.com/menjelangpadam)"
  dark = "auto"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "beranda"
    title = "posts"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "tentang"
    title = "about"
    url = "/about"
    weight = 20
  
  [[menu.main]]
    identifier = "(?)"
    name = "[?]"
    title = "mengapa"
    url = "/why"
    weight = 30

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  #Allows HTML in Markdown
  unsafe = true